### PR TITLE
mc: respect audio player config

### PR DESCRIPTION
**Pull request by cspiel1**
fixes https://github.com/baresip/baresip/issues/3024

Discussion: https://github.com/baresip/baresip/discussions/3022

### CODE REVIEW

**Comment by cspiel1** [comment]
@timmrogers please could you test this?

**Comment by cspiel1** [comment]
I tested this branch successfully with G.722 and `auplay_srate		48000`

**Comment by timmrogers** [comment]
Thank you very much. I look forward to testing it this week!

Thanks again!

*Tim Rogers*
+1 541-221-5834
@timmrogers
Secure email: ***@***.***

**Comment by timmrogers** [comment]
Woo hoo! That resolved my issue. Thank you very much!

**Comment by cspiel1** [comment]
Since this is separated from baresip it is save to merge it.

**Pull request merged**
