### PR TITLE
ua,call: add API for rejecting incoming call

### PR DESCRIPTION
**Pull request by cspiel1**
Implements: https://github.com/baresip/baresip/discussions/3207

### config

The `redirect` module has to be loaded first, at least before module `menu` because it stops the `UA_EVENT_SIPSESS_CONN` event if a redirect is set by the user.

```
# Application Modules

module_app		redirect.so
...
module_app		menu.so

```

### CODE REVIEW

**Comment by cspiel1** [comment]
Did some basic tests.

**Comment by zucher** [comment]
@cspiel1 sure, thank you, I take a look tomorrow.

**Comment by zucher** [comment]
I just take a look shortly on the code, as static setting it's seems fine, but in my currently wish , I expect to manage the hangup rejection on demand dynamically according to the incoming number, so in such case static configuration doesn't fit.

**Comment by cspiel1** [comment]
This sounds useful in general. So, I'll try to find a solution for this. With an async query to the app currently I see the problem, that the answer has to come very quickly from the app in order to avoid sending of SIP retries. But I'll check the details for the timing.

**Comment by zucher** [comment]
but this means not treating the rejection/hhangup at application side but directly into baresip lib due to session depends, not accessible ouside the lib.

**Comment by zucher** [comment]
That's sound good, I'm working with callid's to be able to manage multiple incoming calls at a time. The integration of this function into an app becomes simpler
👍

**Comment by cspiel1** [comment]
Here is what we need in baresip core: https://github.com/baresip/baresip/pull/3228

**Comment by zucher** [comment]
@cspiel1 , Thank you that's working very fine !

**Comment by cspiel1** [comment]
You're welcome!

In order to keep menu/dynamic_menu.c in the baresip repo small and simple I suggest to keep the command `call_redirect` here in this baresip-apps module. Until otherwise requested.

I suggest also to keep the other commands `uaredirect_add`, `uaredirect_clear` and `uaredirect_debug`. They provide the early reject of a SIP INVITE.

**Pull request merged**
