### PR TITLE
ci/build: switch to cmake build

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by cspiel1** [comment]
`-- Found FFMPEG: /usr/lib/x86_64-linux-gnu/libavutil.so (found version "55.78.100") found components: avutil avcodec avfilter avformat swscale swresample avdevice`

But `AVHWDeviceType` is not defined and the compilation fails. I guess there is still a failure in the cmake build for module `avcodec`.

**Comment by cspiel1** [comment]
Here in baresip PR https://github.com/baresip/baresip/pull/2341 I tried to add another cmake check. And the result on github workflow for baresip-apps was:
```
Could NOT find FFMPEG (missing: hwcontext) (found version "55.78.100")
```

But then I saw that `avcodec.h` aready includes `libavutil/hwcontext.h`. A check for `avcodec.h` is already there. So the installation of `libavcodec-dev` on Ubuntu 18.04 might not be complete.

**Comment by sreimers** [comment]
Ubuntu 18.04 is deprecated by github actions, so we should replace it with `ubuntu-22.04`

**Comment by cspiel1** [comment]
Also, for `baresip-apps` maybe we should only build the baresip core as dependency. Right?

**Comment by sreimers** [comment]
On baresip we have this fix for ubuntu 22.04:

```
    - name: Fix Ubuntu 22.04
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get remove libunwind-14 -y
        sudo apt-get install libunwind-dev -y
```

**Comment by cspiel1** [comment]
Not possible to separate from PR https://github.com/baresip/baresip-apps/pull/20.

**Comment by cspiel1** [comment]
It looks good now. @sreimers pls could you review this?

Do you use `act` or something similar to run github actions locally? I had no success with it.

**Comment by sreimers** [comment]
Thanks!

> Do you use `act` or something similar to run github actions locally? I had no success with it.

Nothing local, sometimes I use a simple test repo with simple outputs for debugging.

**Pull request merged**
