### PR TITLE
add docs/examples/config

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by cHuberCoffee** [comment]
multicast config example looks fine to me

**Comment by cspiel1** [comment]
Again the API changed and we didn't notice this. Maybe we find a way to automate a re-build when a baresip PR is merged.

**Comment by cspiel1** [comment]
Saw that the API didn't change. The "missing" function is in main HEAD.

@sreimers The wrong branch of baresip was checked out:
```
Cloning into 'baresip'...
From https://github.com/baresip/baresip
 * [new ref]           refs/pull/2754/head -> jbuf_frame_completeness
Switched to branch 'jbuf_frame_completeness'
```

**Comment by sreimers** [comment]
> The wrong branch of baresip was checked out:

Should be fixed now: https://github.com/baresip/baresip-apps/pull/48

By default, the PR search includes the PR body and comments, this is now limited to the title only.

**Pull request merged**
